modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="ArBeet for making the textures and vectorwing for creating Farmer's Delight"
description="A Farmer's Delight expansion adding spanish cuisine to Minecraft!"
displayURL = "https://github.com/DevJulen/SpanishDelight-1.20.1-Forge"
logoFile = "spanishdelightbanner.png"
logoBlur = true

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.4,)"
ordering = "NONE"
side = "BOTH"